feat: new configuration defaults
OctopusDeploy/api-client.ts pull request #50
Opened 2022-06-20 20:28 UTC by jbristowe

2022-06-20 21:29 UTC, hnrkndrssn requested changes
Looking good, just a few changes we can make to clean up the code a bit. There's also a fair few failing tests which I assume is due to the configuration changes.

2022-06-20 21:29 UTC, hnrkndrssn commented on src/clientConfiguration.ts
> +    };
Shouldn't this also set `autoConnect`?

2022-06-20 21:29 UTC, hnrkndrssn commented on src/client.ts
> +import { processConfiguration } from "./clientConfiguration";
These should be able to be merged together into a single line and the `type` removed

2022-06-20 21:29 UTC, hnrkndrssn commented on src/client.ts
>  import Resolver from "./resolver";
These should be able to be merged together into a single line and the `type` removed

2022-06-20 21:29 UTC, hnrkndrssn commented on src/client.ts
>  import { SubscriptionRecord } from "./subscriptionRecord";
These should be able to be merged together into a single line and the `type` removed

2022-06-20 21:29 UTC, hnrkndrssn commented on src/client.ts
>                  error: (message, er) => {
Can we update the error variable to `err` please

2022-06-20 21:29 UTC, hnrkndrssn commented on src/client.test.ts
> +        await Client.create(clientConfiguration);
Not actually checking that this throws as there's no `expect` calls in the test

2022-06-20 22:41 UTC, domenicsim1 commented on src/apiClient.ts
> +            } else if (error instanceof Error) {
I know this was just a formatting change, but this code block is not safe.  An error in JS is not always an instance of an error object. In JS anything can be thrown, a string, number. We should handle the case when it's not an instance error object too, or we could potentially be swallowing errors.

2022-06-22 04:28 UTC, hnrkndrssn approved these changes
👍

2022-06-22 04:29 UTC, merged